# Generated by Django 4.0.4 on 2022-05-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='nameofdishes',
        ),
    ]
