# Generated by Django 4.0.4 on 2022-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_options_task_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
