# Generated by Django 4.0.4 on 2022-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dishes_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdishes', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('description', models.TextField()),
                ('howTOcook', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
