# Generated by Django 4.0.4 on 2022-05-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dishes2_delete_dishes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dishes2',
            new_name='Dishes',
        ),
    ]
